[package]
name = "exomem"
version = "0.0.0"
edition = "2018"
publish = false
license = "AGPL-3.0-or-later"

[[bin]]
name = "exomem"
path = "src/main.rs"

[dependencies]
clap = "2.33.0"

ui = { package = "exomem-ui", path = "../ui" }