[package]
name = "exomem"
version = "0.0.0"
edition = "2021"
publish = false
license = "AGPL-3.0-or-later"

[dependencies]
clap = { version = "4.1.4", features = [ "derive" ] }

ui = { package = "exomem-ui", path = "../ui" }