[package]
name = "exomem-vault"
version = "0.0.0"
edition = "2021"
publish = false
license = "AGPL-3.0-or-later"

[dependencies]
capnp = "0.16.0"
blake3 = "1.3.3"
base64 = "0.21.0"
bytes = "1.4.0"

[dev-dependencies]
rand = "0.8.5"
