[package]
name = "exomem-vault"
version = "0.0.0"
edition = "2021"
publish = false
license = "AGPL-3.0-or-later"

[dependencies]
capnp = "0.19.2"
blake3 = "1.5.0"
base64 = "0.22.0"
bytes = "1.5.0"

[dev-dependencies]
rand = "0.8.5"
